/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: e6661e352a862c20fe7a470f72648491)
interface __BaseEnv_CloudflareEnv {
	LIFE_IN_BLOOM_UPLOADS: R2Bucket;
	ASSETS: Fetcher;
	DATABASE_URL: string;
	DIRECT_URL: string;
	NEXTAUTH_SECRET: string;
	NEXTAUTH_URL: string;
	KAKAO_CLIENT_ID: string;
	KAKAO_CLIENT_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	NEXT_PUBLIC_PORTONE_CHANNEL_KEY: string;
	PORTONE_API_SECRET: string;
	BLOB_READ_WRITE_TOKEN: string;
	NEXT_PUBLIC_KAKAO_MAP_JAVASCRIPT_KEY: string;
	POLLINATIONS_API_KEY: string;
	NEXT_PUBLIC_SUPABASE_URL: string;
	NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	RESEND_API_KEY: string;
	MAIL_FROM: string;
	DATA_GO_KR_SERVICE_KEY: string;
	AT_FLOWER_API_KEY: string;
	ADMIN_NOTIFICATION_EMAILS: string;
	CLOUDFLARE_API_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	NEXT_PUBLIC_NAVER_MAP_CLIENT_ID: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "DIRECT_URL" | "NEXTAUTH_SECRET" | "NEXTAUTH_URL" | "KAKAO_CLIENT_ID" | "KAKAO_CLIENT_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "NEXT_PUBLIC_PORTONE_CHANNEL_KEY" | "PORTONE_API_SECRET" | "BLOB_READ_WRITE_TOKEN" | "NEXT_PUBLIC_KAKAO_MAP_JAVASCRIPT_KEY" | "POLLINATIONS_API_KEY" | "NEXT_PUBLIC_SUPABASE_URL" | "NEXT_PUBLIC_SUPABASE_ANON_KEY" | "SUPABASE_SERVICE_ROLE_KEY" | "RESEND_API_KEY" | "MAIL_FROM" | "DATA_GO_KR_SERVICE_KEY" | "AT_FLOWER_API_KEY" | "ADMIN_NOTIFICATION_EMAILS" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_ACCOUNT_ID" | "NEXT_PUBLIC_NAVER_MAP_CLIENT_ID">> {}
}
