// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 마이그레이션은 Direct URL 사용 (Supabase 포트 5432)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
