// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
// Prisma CLI는 Next.js와 달리 .env.local을 자동으로 읽지 않으므로 명시적으로 로드
config({ path: ".env.local" });
config(); // .env fallback
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 마이그레이션용: DIRECT_URL에 SSL 강제 적용
    url: (() => {
      const url = process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"] ?? ""
      const base = url.split("?")[0]
      return `${base}?sslmode=require`
    })(),
  },
});
