ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "confirmedAt" TIMESTAMP(3);
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "previewImageUrl" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "composition" JSONB;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "bouquetMode" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "orderItemId" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "previewImageUrl" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "orderMode" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "composition" JSONB;
CREATE UNIQUE INDEX IF NOT EXISTS "Review_orderItemId_key" ON "Review"("orderItemId");
DO $$ BEGIN
  ALTER TABLE "Review" ADD CONSTRAINT "Review_orderItemId_fkey" FOREIGN KEY ("orderItemId") REFERENCES "OrderItem"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
