"use client"

import { useEffect, useState } from "react"
import Link from "next/link"
import { Camera, Sparkles, Star } from "lucide-react"

type Review = { id: string; rating: number; content: string; images: string[]; previewImageUrl: string | null; orderMode: string | null; product: { name: string } | { name: string }[] | null }
export function BouquetGallery({ limit = 4, showViewAll = false }: { limit?: number; showViewAll?: boolean }) {
  const [reviews, setReviews] = useState<Review[]>([])
  useEffect(() => { fetch(`/api/bouquet-reviews?limit=${limit}`).then((r) => r.json()).then((d) => setReviews(d.reviews ?? [])) }, [limit])
  return <section id="bouquet-gallery" className="bg-white px-6 py-20"><div className="mx-auto max-w-6xl"><div className="mb-10 text-center"><h2 className="text-2xl font-bold text-stone-800">📸 손님들의 꽃다발</h2><p className="mt-2 text-sm text-stone-500">AI 꽃다발과 실제 구매 후기를 미리 만나보세요.</p>{showViewAll && <Link href="/gallery" className="mt-3 inline-block text-sm font-medium text-rose-500 underline underline-offset-2">전체 갤러리 보기 →</Link>}</div><div className="grid gap-5 md:grid-cols-2">{reviews.map((review) => { const product = Array.isArray(review.product) ? review.product[0] : review.product; const diy = review.orderMode === "diy"; return <Link href={`/gallery?review=${review.id}`} key={review.id} className="overflow-hidden rounded-3xl border bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="grid grid-cols-2"><Photo src={review.previewImageUrl} ai/><Photo src={review.images[0]}/></div><div className="p-4"><div className="flex justify-between"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${diy ? "bg-emerald-100 text-emerald-700" : "bg-violet-100 text-violet-700"}`}>{diy ? "직접 만들기" : "주문제작"}</span><span className="flex text-amber-400">{[1,2,3,4,5].map((n) => <Star key={n} size={12} className={n <= review.rating ? "fill-current" : "text-stone-200"}/>)}</span></div><p className="mt-3 font-bold text-stone-800">{product?.name ?? "나만의 꽃다발"}</p><p className="mt-1 line-clamp-1 text-xs text-stone-500">{review.content}</p></div></Link> })}</div></div></section>
}
function Photo({ src, ai = false }: { src: string | null; ai?: boolean }) { return <div className={`relative aspect-square ${ai ? "bg-violet-50" : "bg-rose-50"}`}>{src ? <img src={src} alt={ai ? "AI 예상" : "실제 구매 사진"} className="h-full w-full object-cover"/> : <div className="flex h-full items-center justify-center">💐</div>}<span className={`absolute left-2 top-2 rounded-full px-2 py-1 text-[10px] font-bold text-white ${ai ? "bg-violet-600" : "bg-rose-500"}`}>{ai ? <Sparkles size={10} className="mr-1 inline"/> : <Camera size={10} className="mr-1 inline"/>}{ai ? "AI 예상" : "실제 사진"}</span></div>}
